[workspace]
members = [
  "packages/cli",
  "packages/core",
  "packages/pack",
  "packages/providers"
]
default-members = [
  "packages/cli",
  "packages/core",
  "packages/pack",
  "packages/providers"
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.3.2"
license = "MIT"
authors = ["Game Sprite Forge"]
